### ISSUE TITLE
Is `platformName` a mandatory param under Appium W3C spec?

### ISSUE THREAD

**Issue by alliv8** [jlipps/simple-wd-spec#11]
Hello @jlipps ,

[This explanation](https://github.com/dpgraham/appium-w3c-explanation) by @dpgraham  led me here. I wanted to know whether `platformName` is a mandatory server-side capability for appium under w3c, as I don't see it being mandatory for w3c on the selenium side.

And if yes, what is the motivation behind keep it as mandatory as an overlap of platforms doesn't seem to be likely?

**Comment by jlipps** [comment]
I think `platformName` is mandatory for Appium, yes. Appium needs it to find the correct driver. Some drivers support more than one platform. If you have a different opinion about how things should work, I would raise it at the Appium repo!
