### ISSUE TITLE
[Switch To Frame] Incorrect string value for Request Parameters 

### ISSUE THREAD

**Issue by simonradier** [jlipps/simple-wd-spec#13]
Hi @jlipps,

Thanks for this amazing work. During my implementation of a webdriver client, I saw a small error in the Request Parameters part of the [Switch To Frame API](https://github.com/jlipps/simple-wd-spec#switch-to-frame).
It is said : 
```
* null: this represents the top-level browsing context (i.e., not an iframe)
* a Number, representing the index of the window object corresponding to a frame
* a string representing an element id. The element must be the frame or iframe to be selected
```
The last one is not correct, It must be an [web element object](https://w3c.github.io/webdriver/#switch-to-frame) or it will return an error (e.g. : "invalid argument: 'id' can not be string" is returned by Chrome)

A working example would be : 
```
{
    id: { 
        "element-6066-11e4-a52e-4f735466cecf" : "dc876ecc-ddcf-4756-9f59-678413037e29"
    } 
}
```
I hope it helps.

Best regards

**Comment by jlipps** [comment]
hi @simonradier thanks! mind making a PR to fix?

**Comment by simonradier** [comment]
Ho @jlipps,

Done!  (I'm not a native english speaker, you may need to do small edit 🙏🏻 )

Regards,
