### ISSUE TITLE
Can we perform DragAndDrop using Actions.?

### ISSUE THREAD

**Issue by karthik1407s** [jlipps/simple-wd-spec#2]
Hi,
   I am working on desktop application automation. I have a scenario where I need to drag an element and drop in drop zone. I tried dragAndDrop method from webdriverio and its not working. 
can I do this task using  Actions.?

Environment:
webdriverio version: 4.12.0,
node version: 8.11.1

Thanks in Advance
Karthik

**Comment by jlipps** [comment]
@karthik1407s that sounds like a question about a specific implementation of the spec. this repo is about the spec itself, so this is not an appropriate place for that question. you should ask the question in the forums for whatever implementation you're working with (e.g., appium)
