### ISSUE TITLE
need portable and navigatable document for this

### ISSUE THREAD

**Issue by laimis17** [jlipps/simple-wd-spec#6]
this simplified documentation is great. i keep coming for reference.
but there are cases when you offline. Yes i could do pdf export, but still document with table of content would be great!
Thanks

**Comment by jlipps** [comment]
I think simply cloning/downloading the single markdown file, and viewing it in a markdown viewer on your machine, should be sufficient. You could also save the github webpage locally, so that you can view it in a web browser and in-document links will work.
