### ISSUE TITLE
Screenshot and scroll ?

### ISSUE THREAD

**Issue by mlipok** [jlipps/simple-wd-spec#9]
This following part (taken from screenshot) says about scroll parameters, but this is not mentioned here: https://www.w3.org/TR/webdriver/#take-element-screenshot
Please check and confirm what should be done here.

* **Request parameters:** 
	* `scroll`: boolean, whether or not to scroll the element into view before taking the screenshot. Defaults to `true`.
	* Example:
	
		```json
		{"scroll": false}
		```

**Comment by jlipps** [comment]
looks like the spec was updated to always scroll instead of it being optional. can probably just remove the scroll parameter from this guide. care to make a PR?
